export const imageKeys = {
  stadium: "stadium",
  ball: "ball",
  keeperIdle: "keeper-idle",
  psgIdle: "psg-idle",
  bayernIdle: "bayern-idle",
  strikerIdleClean: "striker-idle-clean",
  strikerKickWindupClean: "striker-kick-windup-clean",
  strikerKickFollowthroughClean: "striker-kick-followthrough-clean",
  strikerCelebrateClean: "striker-celebrate-clean",
  strikerDespairClean: "striker-despair-clean",
  bayernStrikerIdleClean: "bayern-striker-idle-clean",
  bayernStrikerKickWindupClean: "bayern-striker-kick-windup-clean",
  bayernStrikerKickFollowthroughClean: "bayern-striker-kick-followthrough-clean",
  bayernStrikerCelebrateClean: "bayern-striker-celebrate-clean",
  bayernStrikerDespairClean: "bayern-striker-despair-clean",
  goalkeeperIdleClean: "goalkeeper-idle-clean",
  goalkeeperDiveLeftClean: "goalkeeper-dive-left-clean",
  goalkeeperDiveRightClean: "goalkeeper-dive-right-clean",
  goalkeeperCatchCenterClean: "goalkeeper-catch-center-clean",
} as const;

export const imagePaths: Record<(typeof imageKeys)[keyof typeof imageKeys], string> = {
  [imageKeys.stadium]: "assets/penalty-background-v1.png",
  [imageKeys.ball]: "assets/sprites/ball.png",
  [imageKeys.keeperIdle]: "assets/sprites/keeper_idle.png",
  [imageKeys.psgIdle]: "assets/sprites/psg_idle.png",
  [imageKeys.bayernIdle]: "assets/sprites/bayern_idle.png",
  [imageKeys.strikerIdleClean]: "assets/sprites/generated/striker_idle_clean.png",
  [imageKeys.strikerKickWindupClean]: "assets/sprites/generated/striker_kick_windup_clean.png",
  [imageKeys.strikerKickFollowthroughClean]: "assets/sprites/generated/striker_kick_followthrough_clean.png",
  [imageKeys.strikerCelebrateClean]: "assets/sprites/generated/striker_celebrate_clean.png",
  [imageKeys.strikerDespairClean]: "assets/sprites/generated/striker_despair_clean.png",
  [imageKeys.bayernStrikerIdleClean]: "assets/sprites/generated/bayern_striker_idle_clean.png",
  [imageKeys.bayernStrikerKickWindupClean]: "assets/sprites/generated/bayern_striker_kick_windup_clean.png",
  [imageKeys.bayernStrikerKickFollowthroughClean]: "assets/sprites/generated/bayern_striker_kick_followthrough_clean.png",
  [imageKeys.bayernStrikerCelebrateClean]: "assets/sprites/generated/bayern_striker_celebrate_clean.png",
  [imageKeys.bayernStrikerDespairClean]: "assets/sprites/generated/bayern_striker_despair_clean.png",
  [imageKeys.goalkeeperIdleClean]: "assets/sprites/generated/goalkeeper_idle_clean.png",
  [imageKeys.goalkeeperDiveLeftClean]: "assets/sprites/generated/goalkeeper_dive_left_clean.png",
  [imageKeys.goalkeeperDiveRightClean]: "assets/sprites/generated/goalkeeper_dive_right_clean.png",
  [imageKeys.goalkeeperCatchCenterClean]: "assets/sprites/generated/goalkeeper_catch_center_clean.png",
};

export const soundKeys = {
  select: "select",
  whistle: "whistle",
  kick: "kick",
  ballImpact: "ball-impact",
  net: "net",
  save: "save",
  miss: "miss",
  crowdCheer: "crowd-cheer",
  crowdGroan: "crowd-groan",
  celebrationStinger: "celebration-stinger",
  stadiumAmbience: "stadium-ambience",
} as const;

export type SoundKey = (typeof soundKeys)[keyof typeof soundKeys];

export const soundPaths: Record<SoundKey, string> = {
  [soundKeys.select]: "assets/audio/select.wav",
  [soundKeys.whistle]: "assets/audio/whistle.wav",
  [soundKeys.kick]: "assets/audio/kick.wav",
  [soundKeys.ballImpact]: "assets/audio/ball-impact.wav",
  [soundKeys.net]: "assets/audio/net.wav",
  [soundKeys.save]: "assets/audio/save.wav",
  [soundKeys.miss]: "assets/audio/miss.wav",
  [soundKeys.crowdCheer]: "assets/audio/crowd-cheer.wav",
  [soundKeys.crowdGroan]: "assets/audio/crowd-groan.wav",
  [soundKeys.celebrationStinger]: "assets/audio/celebration-stinger.wav",
  [soundKeys.stadiumAmbience]: "assets/audio/stadium-ambience.wav",
};
